In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
data=[{'roomno':['1'],'hotelno':['2'],'address':['idk'],
     'das':['dasdsa'],'dsadsa':['dsadsa']},
     {'roomno':['2'],'hotelno':['3'],'address':['igk'],
     'das':['dasdsdsaa'],'dssadadsa':['dsdsadsadsa']}]



In [3]:
pda= pd.DataFrame.from_dict(data)

In [4]:
print(pda)

  roomno hotelno address          das    dsadsa      dssadadsa
0    [1]     [2]   [idk]     [dasdsa]  [dsadsa]            NaN
1    [2]     [3]   [igk]  [dasdsdsaa]       NaN  [dsdsadsadsa]


In [5]:
na=pda.to_csv('friends.csv')

In [6]:
pf=pd.read_csv('friends.csv')

In [7]:
print(pf.to_string())

   Unnamed: 0 roomno hotelno  address            das      dsadsa        dssadadsa
0           0  ['1']   ['2']  ['idk']     ['dasdsa']  ['dsadsa']              NaN
1           1  ['2']   ['3']  ['igk']  ['dasdsdsaa']         NaN  ['dsdsadsadsa']


In [8]:
in_array = [0, math.pi / 2, np.pi / 3, np.pi]

In [9]:
print ("Input array : \n", in_array)

Input array : 
 [0, 1.5707963267948966, 1.0471975511965976, 3.141592653589793]


In [14]:
myarr=np.array([1,2,3,2,31,21,213,123,23,12,312,321,324,314,421,421])

In [15]:
myarr

array([  1,   2,   3,   2,  31,  21, 213, 123,  23,  12, 312, 321, 324,
       314, 421, 421])

In [17]:
myarr.dtype

dtype('int32')

In [18]:
myarr.shape

(16,)

In [19]:
myarr.reshape(4,4)

array([[  1,   2,   3,   2],
       [ 31,  21, 213, 123],
       [ 23,  12, 312, 321],
       [324, 314, 421, 421]])

In [20]:
myarr.shape

(16,)

In [21]:
myara=myarr.reshape(4,4)

In [22]:
myara

array([[  1,   2,   3,   2],
       [ 31,  21, 213, 123],
       [ 23,  12, 312, 321],
       [324, 314, 421, 421]])

In [23]:
myara.shape

(4, 4)

In [35]:
lspace=np.linspace(25,50,11)

In [36]:
lspace

array([25. , 27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. ])

In [37]:
data = {"product_name":["Keyboard","Mouse", "Monitor", "CPU","CPU", "Speakers",pd.NaT],
        "Unit_Price":[500,200, 5000.235, 10000.550, 10000.550, 250.50,None],
        "No_Of_Units":[5,5, 10, 20, 20, 8,pd.NaT],
        "Available_Quantity":[5,6,10,"Not Available","Not Available", pd.NaT,pd.NaT],
        "Available_Since_Date":['11/5/2021', '4/23/2021', '08/21/2021','09/18/2021','09/18/2021','01/05/2021',pd.NaT]
       }


In [41]:
df = pd.DataFrame(data)
df

product_name  Unit_Price No_Of_Units Available_Quantity Available_Since_Date
0     Keyboard     500.000           5                  5            11/5/2021
1        Mouse     200.000           5                  6            4/23/2021
2      Monitor    5000.235          10                 10           08/21/2021
3          CPU   10000.550          20      Not Available           09/18/2021
4          CPU   10000.550          20      Not Available           09/18/2021
5     Speakers     250.500           8                NaT           01/05/2021
6          NaT         NaN         NaT                NaT                  NaT

In [43]:
df.drop([5,6], axis=0, inplace=True)

In [44]:
df

product_name  Unit_Price No_Of_Units Available_Quantity Available_Since_Date
0     Keyboard     500.000           5                  5            11/5/2021
1        Mouse     200.000           5                  6            4/23/2021
2      Monitor    5000.235          10                 10           08/21/2021
3          CPU   10000.550          20      Not Available           09/18/2021
4          CPU   10000.550          20      Not Available           09/18/2021